# Generated by Django 5.1.2 on 2024-11-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
